### ISSUE TITLE
Dataset Not a part of the notebook

### ISSUE THREAD

**Issue by InfinityOrb** [alpercakr/Planet-Hunting-and-Habitability-Detection-with-Machine-Learning#1]
Hi! I wanted to tinker around with this code a little because its very fascinating but since the dataset 'exoplanets.csv' is not available, I can't run it.
Is there any way I can get that data? I can't find it on the provided link either.
Love your work,
Thanks

**Comment by alpercakr** [comment]
Hi,
I got the data from two sources. Nasa's exoplanet archive and phl. Here are the links for them: 
https://phl.upr.edu/data
https://exoplanetarchive.ipac.caltech.edu/

**Comment by InfinityOrb** [comment]
Thanks!
I had one more question, did you download the columns checked by default or omit some of them?
I'm trying a school project so the exact dataset or csv file would be amazing but if not, I'd appreciate some guidance on how you got the data to work because I assume the specific operations you did with removing some columns were based specifically on your csv. (I'm kinda new to this sorry)
Thanks for responding!

**Comment by alpercakr** [comment]
Yes, I made changes as needed. You can see the processing code in the habitability detection file. Also, I added CSV file of the data. I hope it serves your needs. Good luck

**Comment by InfinityOrb** [comment]
Thank you so much! I appreciate this a lot. 
Have a great week.
